services:
  - type: web
    name: ecommerce-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: ecommerce-db
    plan: free